[versions]
agp = "8.12.3"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activityCompose = "1.10.1"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.13.1"
androidx-espresso-core = "3.6.1"
androidx-lifecycle = "2.8.4"
androidx-material = "1.12.0"
androidx-test-junit = "1.2.1"
compose-multiplatform = "1.8.1"
desugar_jdk_libs = "2.1.5"
firebase = "2.4.0"
firebaseiOSSDK = "12.4.0"
firebaseJavaSdk = "0.6.3"
junit = "4.13.2"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
googleService = "4.4.4"
spmForKmp = "1.4.7"
coroutines = "1.10.2"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
firebase-java-sdk = { module = "dev.gitlive:firebase-java-sdk", version.ref = "firebaseJavaSdk" }
firebase-perf = { module = "dev.gitlive:firebase-perf", version.ref = "firebase" }
firebase-config = { module = "dev.gitlive:firebase-config", version.ref = "firebase" }
firebase-installations = { module = "dev.gitlive:firebase-installations", version.ref = "firebase" }
firebase-storage = { module = "dev.gitlive:firebase-storage", version.ref = "firebase" }
firebase-messaging = { module = "dev.gitlive:firebase-messaging", version.ref = "firebase" }
firebase-functions = { module = "dev.gitlive:firebase-functions", version.ref = "firebase" }
firebase-firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "firebase" }
firebase-database = { module = "dev.gitlive:firebase-database", version.ref = "firebase" }
firebase-analytics = { module = "dev.gitlive:firebase-analytics", version.ref = "firebase" }
firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "firebase" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
googleService = { id = "com.google.gms.google-services", version.ref = "googleService" }
spmForKmp = { id = "io.github.frankois944.spmForKmp", version.ref = "spmForKmp" }